#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build \
  -f Dockerfile.alpine
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VERSION=$(git describe --tags) \
  --build-arg VCS_URL=$(git config --get remote.origin.url) \
  --build-arg VCS_BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  -t $IMAGE_NAME .
